[package]
name = "disrust-captioner"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
cpal = "0.11"
pyannote-rs = "0.1"
whisper-rs = "0.1"
egui = "0.14"
iced = "0.3"
serde = "1.0"
serde_json = "1.0"
